# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Github Actions Java CI with Maven
# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches: [ dev ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - chechout dev branch from Github
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Step 4 - List the current directory
      run: ls -a
      
    - name: Step 5 - Check in the target folder
      run: |
        cd target
        ls -a
